name: Flutter CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
      
    - name: Analyze project source
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
  build-android:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build optimized APK
      run: |
        flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64
        flutter build apk --release --target-platform android-arm,android-arm64,android-x64
      
    - name: Get app version
      id: version
      run: |
        VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f2 | tr -d '\r')
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        release_name: CalmConnect v${{ steps.version.outputs.VERSION }}
        body: |
          ## 🚀 CalmConnect Release v${{ steps.version.outputs.VERSION }}
          
          ### 📱 Download Options
          - **Universal APK**: Compatible with all Android devices
          - **ARM64 APK**: Optimized for modern 64-bit devices (recommended)
          - **ARM32 APK**: For older 32-bit devices
          - **x64 APK**: For x86 Android devices
          
          ### ✨ Features
          - Mental health peer support platform
          - Real-time chat with counselors
          - Professional resource directory
          - Daily wellness tips and self-care tools
          
          ### 🛠️ Technical Details
          - **Minimum Android Version**: 5.0 (API 21)
          - **Target Android Version**: 14 (API 34)
          - **Architecture Support**: ARM32, ARM64, x64
          
          ### 📋 Installation
          1. Download the APK file
          2. Enable "Install from Unknown Sources" in Android settings
          3. Install and enjoy CalmConnect!
        draft: false
        prerelease: false
        
    - name: Upload Universal APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: CalmConnect-v${{ steps.version.outputs.VERSION }}-universal.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: Upload ARM64 APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
        asset_name: CalmConnect-v${{ steps.version.outputs.VERSION }}-arm64.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: Upload ARM32 APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
        asset_name: CalmConnect-v${{ steps.version.outputs.VERSION }}-arm32.apk
        asset_content_type: application/vnd.android.package-archive
        
  build-ios:
    needs: test
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build iOS (no code signing)
      run: flutter build ios --release --no-codesign
      
    - name: Archive iOS build
      run: |
        cd build/ios/iphoneos
        tar -czf ios-build.tar.gz Runner.app